version: '3.0'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - client
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
    
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_SERVER_PORT=443
      - VITE_APP_ENV=docker

volumes:
  mongo_data: {}
