# Use an official Node runtime as a parent image
FROM node:19-slim as build
# Set the working directory to /app
WORKDIR /app
RUN npm i -g nodemon
# Copy the package.json and package-lock.json to the container
COPY package*.json ./
# Install dependencies
RUN npm i
# Copy the rest of the application code to the container
COPY . .
# Expose the port the app runs on
EXPOSE 5000
# Build the React app
CMD ["npm", "run", "dev"]
