FROM nginx
COPY ./cert/certs/pawianek.local.crt /etc/nginx/ssl/cert/certs/pawianek.local.crt
COPY ./cert/certs/pawianek.local.key /etc/nginx/ssl/cert/certs/pawianek.local.key
COPY ./default.conf /etc/nginx/conf.d/default.conf